"use client";

import Link from "next/link";
import { BarChart3, BrainCircuit, Database, LayoutDashboard, ShieldCheck } from "lucide-react";
import type { ReactNode } from "react";
import { cn } from "@/lib/utils";

export function AppShell({ active, children }: { active: "monitoring" | "analysis"; children: ReactNode }) {
  return <div className="min-h-screen bg-[#f3f0e9] text-[#272622]"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col bg-[#1f201e] px-5 py-7 text-white lg:flex"><Link href="/" className="flex items-center gap-3 rounded-xl px-2 focus-visible:outline-2 focus-visible:outline-[#d7bb7a]"><span className="grid size-10 place-items-center rounded-xl border border-[#b99955]/40 bg-[#b99955]/10 text-[#d7bb7a]"><BarChart3 className="size-5" /></span><span><b className="block tracking-[-0.03em]">DanA-F</b><span className="text-[10px] uppercase tracking-[0.18em] text-[#9c9a91]">Portfolio intelligence</span></span></Link><nav className="mt-12 space-y-2" aria-label="Primary navigation"><ShellLink href="/" active={active === "monitoring"} icon={<LayoutDashboard className="size-4" />}>Monitoring</ShellLink><ShellLink href="/analysis" active={active === "analysis"} icon={<BrainCircuit className="size-4" />}>Deep Dive</ShellLink></nav><div className="mt-auto rounded-2xl border border-white/[0.08] bg-white/[0.04] p-4"><p className="flex items-center gap-2 text-xs font-medium"><ShieldCheck className="size-4 text-[#d7bb7a]" /> Private by default</p><p className="mt-2 text-[11px] leading-5 text-[#929088]">Monitoring stays local. Deep Dive shares a snapshot only after consent.</p></div></aside><div className="lg:ml-64"><header className="sticky top-0 z-20 border-b border-[#dfdbd1] bg-[#f8f6f1]/90 px-4 py-3 backdrop-blur-xl sm:px-7 lg:px-10"><div className="mx-auto flex max-w-[1440px] items-center justify-between"><Link href="/" className="flex items-center gap-2 font-semibold lg:hidden"><BarChart3 className="size-5 text-[#9b7b3f]" />DanA-F</Link><p className="hidden text-xs text-[#77736a] lg:block">Daniel Agent Finance</p><p className="flex items-center gap-2 text-[11px] text-[#706c63]"><Database className="size-3.5 text-[#9d854e]" /> Local-first</p></div></header><main className="mx-auto max-w-[1440px] px-4 py-7 pb-24 sm:px-7 lg:px-10 lg:py-9">{children}</main><nav className="fixed inset-x-3 bottom-3 z-30 flex justify-around rounded-2xl border border-[#ded9ce] bg-[#1f201e]/95 p-2 shadow-xl backdrop-blur lg:hidden" aria-label="Mobile navigation"><ShellLink href="/" active={active === "monitoring"} icon={<LayoutDashboard className="size-4" />}>Monitoring</ShellLink><ShellLink href="/analysis" active={active === "analysis"} icon={<BrainCircuit className="size-4" />}>Deep Dive</ShellLink></nav></div></div>;
}

function ShellLink({ href, active, icon, children }: { href: string; active: boolean; icon: ReactNode; children: ReactNode }) { return <Link href={href} className={cn("flex min-h-11 items-center gap-3 rounded-xl px-3 py-2 text-sm transition-colors focus-visible:outline-2 focus-visible:outline-[#d7bb7a]", active ? "bg-white/[0.09] font-medium text-white" : "text-[#aaa89f] hover:bg-white/[0.05] hover:text-white")}>{icon}{children}</Link>; }
